# Generated by Django 5.2.4 on 2025-08-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0001_initial"),
        ("seekers", "0002_alter_message_options_alter_message_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeker_messages",
                to="landlords.conversation",
            ),
        ),
    ]
