# Generated by Django 5.2.4 on 2025-09-15 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0004_alter_message_options_message_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeker_sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
