# Generated by Django 5.2.4 on 2025-09-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0005_alter_message_sender"),
    ]

    operations = []
