# Generated by Django 5.2.4 on 2025-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0006_auto_20250927_1024"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
