# Generated by Django 5.2.7 on 2026-03-11 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landlords",
            "0007_alter_amenity_options_alter_communitypost_options_and_more",
        ),
        ("seekers", "0007_delete_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitypost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="savedproperty",
            old_name="property",
            new_name="listing",
        ),
        migrations.AlterField(
            model_name="seekerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="seekerprofile",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name="savedproperty",
            unique_together={("seeker", "listing")},
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(fields=["-created_at"], name="post_created_idx"),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["author", "-created_at"], name="post_author_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(fields=["location_tag"], name="post_location_idx"),
        ),
        migrations.AddIndex(
            model_name="communityreply",
            index=models.Index(fields=["post", "created_at"], name="reply_post_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="savedproperty",
            index=models.Index(
                fields=["seeker", "-created_at"], name="saved_seeker_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seekerprofile",
            index=models.Index(fields=["verified"], name="seeker_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="seekerprofile",
            index=models.Index(
                fields=["employment_status"], name="seeker_employment_idx"
            ),
        ),
    ]
