# Generated by Django 5.2.7 on 2025-10-16 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_account_locked_until_user_failed_login_attempts_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securitylog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Security Log",
                "verbose_name_plural": "Security Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="trusteddevice",
            options={
                "verbose_name": "Trusted Device",
                "verbose_name_plural": "Trusted Devices",
            },
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trusted_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
