# Generated by Django 5.2.7 on 2026-01-30 16:35

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_securitylog_options_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="trusteddevice",
            options={
                "ordering": ["-last_used"],
                "verbose_name": "Trusted Device",
                "verbose_name_plural": "Trusted Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="securitylog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2026, 1, 30, 10, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("REGISTER", "User Registration"),
                    ("LOGIN", "Successful Login"),
                    ("LOGIN_MFA", "MFA Login"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_RESET", "Password Reset Request"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("MFA_ENABLED", "MFA Enabled"),
                    ("MFA_DISABLED", "MFA Disabled"),
                    ("DEVICE_ADDED", "Trusted Device Added"),
                    ("DEVICE_REMOVED", "Trusted Device Removed"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("SUSPICIOUS_ACTIVITY", "Suspicious Activity Detected"),
                    ("ACCESS_DENIED", "Access Denied"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="ip_address",
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("both", "Both"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="accounts_se_user_id_e4a21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["action", "-timestamp"], name="accounts_se_action_5992c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="accounts_se_ip_addr_0caf31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_tr_user_id_2c6d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trusteddevice",
            index=models.Index(
                fields=["device_id"], name="accounts_tr_device__6f6a7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "email_verified"], name="accounts_us_email_6db061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="accounts_us_phone_n_613c4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_locked_until"], name="accounts_us_account_4ad689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["identifier", "-timestamp"],
                name="accounts_lo_identif_fc6d9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="accounts_lo_ip_addr_eed231_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["success", "-timestamp"], name="accounts_lo_success_472f8a_idx"
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
