# Generated by Django 5.2.7 on 2026-03-11 18:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_loginattempt_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="login_ident_ts_idx",
            old_name="accounts_lo_identif_fc6d9e_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="login_ip_ts_idx",
            old_name="accounts_lo_ip_addr_eed231_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="login_success_ts_idx",
            old_name="accounts_lo_success_472f8a_idx",
        ),
        migrations.RenameIndex(
            model_name="securitylog",
            new_name="seclog_user_ts_idx",
            old_name="accounts_se_user_id_e4a21e_idx",
        ),
        migrations.RenameIndex(
            model_name="securitylog",
            new_name="seclog_action_ts_idx",
            old_name="accounts_se_action_5992c9_idx",
        ),
        migrations.RenameIndex(
            model_name="securitylog",
            new_name="seclog_ip_ts_idx",
            old_name="accounts_se_ip_addr_0caf31_idx",
        ),
        migrations.RenameIndex(
            model_name="trusteddevice",
            new_name="device_user_active_idx",
            old_name="accounts_tr_user_id_2c6d45_idx",
        ),
        migrations.RenameIndex(
            model_name="trusteddevice",
            new_name="device_id_idx",
            old_name="accounts_tr_device__6f6a7d_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_email_verified_idx",
            old_name="accounts_us_email_6db061_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_phone_idx",
            old_name="accounts_us_phone_n_613c4a_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_type_idx",
            old_name="accounts_us_user_ty_b6cfc8_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="user_locked_idx",
            old_name="accounts_us_account_4ad689_idx",
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="identifier",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="success",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("REGISTER", "User Registration"),
                    ("LOGIN", "Successful Login"),
                    ("LOGIN_MFA", "MFA Login"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_RESET", "Password Reset Request"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("MFA_ENABLED", "MFA Enabled"),
                    ("MFA_DISABLED", "MFA Disabled"),
                    ("DEVICE_ADDED", "Trusted Device Added"),
                    ("DEVICE_REMOVED", "Trusted Device Removed"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("SUSPICIOUS_ACTIVITY", "Suspicious Activity Detected"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("BACKUP_CODES_REGENERATED", "Backup Codes Regenerated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("email", "Email OTP"),
                    ("google_authenticator", "Google Authenticator"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+999999999'. Up to 15 digits.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("both", "Both"),
                    ("admin", "Admin"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token"], name="prt_token_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["user", "used"], name="prt_user_used_idx"),
        ),
    ]
