# Generated by Django 5.2.4 on 2025-09-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={"ordering": ["-is_primary", "uploaded_at"]},
        ),
    ]
