# Generated by Django 5.2.4 on 2025-09-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0003_alter_conversation_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="last_message",
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_messages",
                to="landlords.conversation",
            ),
        ),
    ]
