# Generated by Django 5.2.4 on 2025-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0004_remove_conversation_last_message_and_more"),
    ]

    operations = []
