# Generated by Django 5.2.4 on 2025-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlords", "0005_auto_20250927_1025"),
        ("seekers", "0007_delete_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="message",
            name="property",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
