# Generated by Django 5.2.7 on 2026-03-11 17:33

import django.core.validators
import landlords.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landlords",
            "0006_remove_message_conversation_remove_message_property_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"ordering": ["name"], "verbose_name_plural": "Amenities"},
        ),
        migrations.AlterModelOptions(
            name="communitypost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="after_photos",
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="before_photos",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="after_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="maintenance/after/",
                validators=[landlords.models.validate_property_image],
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="before_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="maintenance/before/",
                validators=[landlords.models.validate_property_image],
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("landlords", "Landlords Only"),
                    ("all", "All Users (Seekers & Landlords)"),
                ],
                db_index=True,
                default="all",
                help_text="Who can view this post?",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("repair", "Repair"),
                    ("maintenance", "Maintenance"),
                    ("utility", "Utility"),
                    ("tax", "Tax"),
                    ("insurance", "Insurance"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="landlordprofile",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="landlordprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="landlord_profile_pics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    landlords.models.validate_profile_picture,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="leaseagreement",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("emergency", "Emergency"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("property", "Property"),
                    ("application", "Application"),
                    ("verification", "Verification"),
                    ("account", "Account"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Publish on marketplace"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("commercial", "Commercial Space"),
                    ("land", "Land"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="verification_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                upload_to="property_images/",
                validators=[landlords.models.validate_property_image],
            ),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["is_verified"], name="landlords_l_is_veri_25a460_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="notification_unread_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_published", "is_active", "-is_featured", "-created_at"],
                name="property_listing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["landlord", "is_active"], name="property_landlord_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["property", "email"], name="tenant_property_email_idx"
            ),
        ),
    ]
